### ISSUE TITLE
User Story 12: View menu item images

### ISSUE THREAD

**Issue by BadrAlioui** [BadrAlioui/forthProject#12]
### User Story 12: View menu item images
**As a user, I want to see images of the menu items so that I can make my choices based on the presentation of the food.**

#### Acceptance Criteria:
- Menu items include images.
- Images are clear and optimized for all devices.

#### Tasks:
- [ ] Add an image upload field to the menu item model.
- [ ] Display uploaded images on the menu page.
- [ ] Optimize image size for performance and responsiveness.
