### ISSUE TITLE
User Story 9: Access menu page

### ISSUE THREAD

**Issue by BadrAlioui** [BadrAlioui/forthProject#9]
### User Story 9: Access menu page
**As a user, I want to access the menu page to see the available dishes before making a reservation.**

#### Acceptance Criteria:
- A menu page is accessible from the navigation bar.
- The menu displays a list of available dishes with images.

#### Tasks:
- [ ] Create a menu page template.
- [ ] Add links to the menu page in the navigation bar.
- [ ] Display menu items with images, names, and prices.

**Comment by jjyutm4532** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added a link to the menu page in the navigation bar and created a menu list page to display available dishes with images, names, and prices.

You can review changes in this commit: https://github.com/jjyutm4532/BadrAlioui-forthProject-9/commit/44472f5e3a9d4a6175c9838603ea7bab57c8c22d.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
